import Scene from "./Scene";

function Level1() {
    const mapString = `GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG/GGGGGGGGGGGGGGGGG`
    const mapArr2 = [
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGPPPPPPPPPPPPPPPPPGGGGGGG/", 
        "PPPPPPPPPGGGGGGGGGGGGGGGPPPPGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGPGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGPPPGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGPPPPPPGGGGGG/", 
        "GGGGGGGGGPPPPPPPPPPPPGGGGGGGGGGG/", 
        "GGGGGGPPPPGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGPGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGPGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGPPPPPGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGPPPPPPPPGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGPPPPPPPPPPGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPP/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    ]

    const mapArr = [
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",  
    ]

    const backgroundArr = [
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
    ]

    return <Scene mapString={ mapArr.join("") } mapWidth={mapArr[1].length - 1} mapHeight={mapArr.length}> </Scene>;
}

export default Level1;