import Scene from "./Scene";

function Level1() {
    
    const mapArr = [
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "SPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG/", 
        "EPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG/", 
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",  
    ]

    const pathDirectionsArr = [["R", 29], ["D", 4], ["L", 27], ["D", 4], ["R", 27], ["D", 4], ["L", 29]];
    let pathDirections = "";

    // converting path array to an array
    for (let i = 0; i < pathDirectionsArr.length; i++) {
        for (let j = 0; j < pathDirectionsArr[i][1]; j++) {
            pathDirections += pathDirectionsArr[i][0];
        }
    }

    const backgroundArr = [
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/",
    ]



    return <Scene mapString={ mapArr.join("") } mapWidth={mapArr[1].length - 1} mapHeight={mapArr.length} pathDirections={pathDirections}> </Scene>;
}

export default Level1;